import { SessionRepository } from "@/domain/session/SessionRepository";
import { UserRepository } from "@/domain/user/UserRepository";
import { ShareToken } from "@/domain/session/ShareToken";
import { OwnerToken } from "@/domain/session/OwnerToken";
import { EstimationSession } from "@/domain/session/EstimationSession";
import { UnauthorizedError } from "@/domain/errors/DomainError";

export interface CreateSessionInput {
  name?: string;
  projectId?: string;
  ownerId?: string;
}

export interface CreateSessionOutput {
  id: string;
  name: string | null;
  shareToken: string;
  ownerToken: string;
  projectId: string | null;
  ownerId: string | null;
  isRevealed: boolean;
  status: string;
  createdAt: Date;
}

/**
 * セッション作成ユースケース
 *
 * ビジネスルール:
 * - ゲストユーザーでもセッションを作成できる
 * - プロジェクトに紐づけるにはownerIdが必要
 * - ShareTokenとOwnerTokenを自動生成
 */
export class CreateSessionUseCase {
  constructor(
    private sessionRepository: SessionRepository,
    private userRepository: UserRepository
  ) {}

  async execute(input: CreateSessionInput): Promise<CreateSessionOutput> {
    // ownerIdが指定されている場合、ユーザーの存在を確認
    if (input.ownerId) {
      const owner = await this.userRepository.findById(input.ownerId);
      if (!owner) {
        throw new UnauthorizedError("User not found");
      }
    }

    // トークン生成
    const shareToken = await ShareToken.generate();
    const ownerToken = await OwnerToken.generate();

    // セッション作成
    const session = EstimationSession.create(
      "", // id (will be generated by repository)
      input.name || null,
      shareToken,
      ownerToken,
      input.ownerId || null,
      input.projectId || null
    );

    // 永続化
    const savedSession = await this.sessionRepository.save(session);

    return {
      id: savedSession.id,
      name: savedSession.name,
      shareToken: savedSession.shareToken.value,
      ownerToken: savedSession.ownerToken.value,
      projectId: savedSession.projectId,
      ownerId: savedSession.ownerId,
      isRevealed: savedSession.isRevealed,
      status: savedSession.status,
      createdAt: savedSession.createdAt,
    };
  }
}
