import { SessionRepository } from "@/domain/session/SessionRepository";
import { EstimateRepository } from "@/domain/session/EstimateRepository";
import { UserRepository } from "@/domain/user/UserRepository";
import { ShareToken } from "@/domain/session/ShareToken";
import { Estimate } from "@/domain/session/Estimate";
import { NotFoundError, ValidationError } from "@/domain/errors/DomainError";

export interface SubmitEstimateInput {
  shareToken: string;
  userId: string;
  nickname: string;
  value: number;
}

export interface SubmitEstimateOutput {
  id: string;
  sessionId: string;
  userId: string;
  nickname: string;
  value: number;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * 見積もり投稿ユースケース
 *
 * ビジネスルール:
 * - セッションが存在し、アクティブであること
 * - 同じユーザーによる再投稿は上書き
 * - 見積もり値は0以上
 */
export class SubmitEstimateUseCase {
  constructor(
    private sessionRepository: SessionRepository,
    private estimateRepository: EstimateRepository,
    private userRepository: UserRepository
  ) {}

  async execute(input: SubmitEstimateInput): Promise<SubmitEstimateOutput> {
    // セッション存在確認
    const shareToken = ShareToken.fromString(input.shareToken);
    const session = await this.sessionRepository.findByShareToken(shareToken);
    if (!session) {
      throw new NotFoundError(`Session not found with shareToken: ${input.shareToken}`);
    }

    // ファイナライズ済みセッションには投稿不可
    if (session.isFinalized()) {
      throw new ValidationError("Cannot submit estimate to finalized session");
    }

    // ユーザー存在確認
    const user = await this.userRepository.findById(input.userId);
    if (!user) {
      throw new NotFoundError(`User not found: ${input.userId}`);
    }

    // 既存の見積もりを検索
    const existingEstimate = await this.estimateRepository.findBySessionAndUser(
      session.id,
      input.userId
    );

    let estimate: Estimate;

    if (existingEstimate) {
      // 既存見積もりの更新
      estimate = existingEstimate.update(input.value);
      estimate = await this.estimateRepository.save(estimate);
    } else {
      // 新規見積もりの作成
      estimate = Estimate.create(
        "", // id (will be generated by repository)
        session.id,
        input.userId,
        input.nickname,
        input.value
      );
      estimate = await this.estimateRepository.save(estimate);
    }

    return {
      id: estimate.id,
      sessionId: estimate.sessionId,
      userId: estimate.userId,
      nickname: estimate.nickname,
      value: estimate.value,
      createdAt: estimate.createdAt,
      updatedAt: estimate.updatedAt,
    };
  }
}
