import { SessionRepository } from "@/domain/session/SessionRepository";
import { ProjectRepository } from "@/domain/project/ProjectRepository";
import { EstimationSession } from "@/domain/session/EstimationSession";
import { ShareToken } from "@/domain/session/ShareToken";
import { OwnerToken } from "@/domain/session/OwnerToken";
import { NotFoundError, UnauthorizedError } from "@/domain/errors/DomainError";

export interface CreateProjectSessionInput {
  projectId: string;
  requestUserId: string;
  name?: string;
}

export interface CreateProjectSessionOutput {
  sessionId: string;
  shareToken: string;
  ownerToken: string;
  name: string | null;
}

/**
 * プロジェクト配下にセッションを作成するユースケース
 *
 * ビジネスルール:
 * - プロジェクトのオーナーのみがセッションを作成可能
 * - セッションは自動的にプロジェクトに紐づけられる
 */
export class CreateProjectSessionUseCase {
  constructor(
    private projectRepository: ProjectRepository,
    private sessionRepository: SessionRepository
  ) {}

  async execute(
    input: CreateProjectSessionInput
  ): Promise<CreateProjectSessionOutput> {
    // プロジェクト取得
    const project = await this.projectRepository.findById(input.projectId);

    if (!project) {
      throw new NotFoundError(`Project not found: ${input.projectId}`);
    }

    // オーナー確認
    if (!project.isOwnedBy(input.requestUserId)) {
      throw new UnauthorizedError("You are not the owner of this project");
    }

    // トークン生成
    const shareToken = await ShareToken.generate();
    const ownerToken = await OwnerToken.generate();

    // セッション作成
    const session = EstimationSession.create(
      "", // id (will be generated by repository)
      input.name?.trim() || null,
      shareToken,
      ownerToken,
      input.requestUserId,
      input.projectId
    );

    // 永続化
    const savedSession = await this.sessionRepository.save(session);

    return {
      sessionId: savedSession.id,
      shareToken: savedSession.shareToken.value,
      ownerToken: savedSession.ownerToken.value,
      name: savedSession.name,
    };
  }
}
