import { ProjectRepository } from "@/domain/project/ProjectRepository";
import { UserRepository } from "@/domain/user/UserRepository";
import { Project } from "@/domain/project/Project";
import { NotFoundError, UnauthorizedError, ValidationError } from "@/domain/errors/DomainError";

export interface CreateProjectInput {
  name: string;
  description?: string;
  ownerId: string;
}

export interface CreateProjectOutput {
  id: string;
  name: string;
  description: string | null;
  ownerId: string;
  createdAt: Date;
}

/**
 * プロジェクト作成ユースケース
 *
 * ビジネスルール:
 * - 認証済みユーザーのみがプロジェクトを作成可能
 * - ゲストユーザーはプロジェクトを作成できない
 * - プロジェクト名は必須
 */
export class CreateProjectUseCase {
  constructor(
    private projectRepository: ProjectRepository,
    private userRepository: UserRepository
  ) {}

  async execute(input: CreateProjectInput): Promise<CreateProjectOutput> {
    // バリデーション
    if (!input.name || input.name.trim() === "") {
      throw new ValidationError("Project name is required");
    }

    // ユーザー存在確認
    const user = await this.userRepository.findById(input.ownerId);
    if (!user) {
      throw new NotFoundError(`User not found: ${input.ownerId}`);
    }

    // ゲストユーザーはプロジェクト作成不可
    if (!user.canManageProjects()) {
      throw new UnauthorizedError("Guest users cannot create projects");
    }

    // プロジェクト作成
    const project = Project.create(
      "", // id (will be generated by repository)
      input.name.trim(),
      input.description?.trim() || null,
      input.ownerId
    );

    // 永続化
    const savedProject = await this.projectRepository.save(project);

    return {
      id: savedProject.id,
      name: savedProject.name,
      description: savedProject.description,
      ownerId: savedProject.ownerId,
      createdAt: savedProject.createdAt,
    };
  }
}
