import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/infrastructure/database/prisma'
import { CreateSessionUseCase } from '@/application/session/CreateSessionUseCase'
import { CreateGuestUserUseCase } from '@/application/auth/CreateGuestUserUseCase'
import { PrismaSessionRepository } from '@/infrastructure/database/repositories/PrismaSessionRepository'
import { PrismaUserRepository } from '@/infrastructure/database/repositories/PrismaUserRepository'
import { PrismaEstimateRepository } from '@/infrastructure/database/repositories/PrismaEstimateRepository'
import { Estimate } from '@/domain/session/Estimate'

// POST /api/sessions - セッションを作成
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { nickname, userId, name, projectId } = body

    if (!nickname || typeof nickname !== 'string' || nickname.trim() === '') {
      return NextResponse.json(
        { error: 'ニックネームを入力してください' },
        { status: 400 }
      )
    }

    // リポジトリのインスタンス化
    const userRepository = new PrismaUserRepository(prisma)
    const sessionRepository = new PrismaSessionRepository(prisma)
    const estimateRepository = new PrismaEstimateRepository(prisma)

    // ユーザーIDが提供されていない場合、新規ゲストユーザーを作成
    let actualUserId = userId
    if (!actualUserId) {
      const createGuestUserUseCase = new CreateGuestUserUseCase(userRepository)
      const user = await createGuestUserUseCase.execute(nickname.trim())
      actualUserId = user.id
    }

    // セッション作成
    const createSessionUseCase = new CreateSessionUseCase(sessionRepository, userRepository)
    const session = await createSessionUseCase.execute({
      name: name && typeof name === 'string' && name.trim() !== '' ? name.trim() : undefined,
      projectId: projectId || undefined,
      ownerId: actualUserId,
    })

    // 作成者の見積もりエントリを作成
    const estimate = Estimate.create(
      "", // id (will be generated by repository)
      session.id,
      actualUserId,
      nickname.trim(),
      0 // 初期値
    )
    await estimateRepository.save(estimate)

    const protocol = request.headers.get('x-forwarded-proto') || 'http'
    const host = request.headers.get('host') || 'localhost:3000'
    const shareUrl = `${protocol}://${host}/estimate/${session.shareToken}`

    return NextResponse.json({
      sessionId: session.id,
      shareToken: session.shareToken,
      ownerToken: session.ownerToken,
      shareUrl,
      userId: actualUserId
    })
  } catch (error) {
    // 詳細なエラー情報をサーバーログに記録
    console.error('Session creation error:', {
      error,
      errorMessage: error instanceof Error ? error.message : 'Unknown error',
      errorStack: error instanceof Error ? error.stack : undefined,
      errorName: error instanceof Error ? error.name : undefined,
    })

    return NextResponse.json(
      { error: 'セッションの作成に失敗しました' },
      { status: 500 }
    )
  }
}
